name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Build with Rusttls
        run: cargo build --verbose --no-default-features --features rust-tls
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests with rust-tls
        run: cargo test --verbose --no-default-features --features rust-tls
